project_id = "bahshstcztvqmxiubslx"

[functions.secure-api-proxy]
verify_jwt = false

[functions.secure-coingecko-proxy]
verify_jwt = false

[functions.dune-fetch]
verify_jwt = false

[functions.onchain-oracle]
verify_jwt = false
