project_id = "bahshstcztvqmxiubslx"

[functions.secure-api-proxy]
verify_jwt = false

[functions.secure-coingecko-proxy]
verify_jwt = false

[functions.dune-fetch]
verify_jwt = false

[functions.onchain-oracle]
verify_jwt = false

[functions.populate-crypto-signals]
verify_jwt = false

[functions.secure-market-data-fetcher]
verify_jwt = false

[functions.secure-gemini-proxy]
verify_jwt = false

[functions.crypto-data-collector]
verify_jwt = false

[functions.coinglass-fetcher]
verify_jwt = false

[functions.temp-migration-func]
verify_jwt = false

[functions.populate-price-history]
verify_jwt = false

[functions.populate-watchlist-signals]
verify_jwt = false

[functions.populate-multiple-price-history]
verify_jwt = false
