project_id = "bahshstcztvqmxiubslx"

[functions.secure-api-proxy]
verify_jwt = false

[functions.secure-coingecko-proxy]
verify_jwt = false

[functions.dune-fetch]
verify_jwt = false

[functions.onchain-oracle]
verify_jwt = false

[functions.temp-migration-func]
enabled = true
verify_jwt = true
import_map = "./functions/temp-migration-func/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/temp-migration-func/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/temp-migration-func/*.html" ]

[functions.populate-price-history]
enabled = true
verify_jwt = true
import_map = "./functions/populate-price-history/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/populate-price-history/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/populate-price-history/*.html" ]
