
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL || 'https://bahshstcztvqmxiubslx.supabase.co';
const service_role_key = process.env.SUPABASE_SERVICE_ROLE_KEY; // Using service role key for DDL operations

if (!service_role_key) {
    console.error('SUPABASE_SERVICE_ROLE_KEY environment variable is not set.');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, service_role_key);

const createTableSql = `
  CREATE TABLE IF NOT EXISTS public.ai_watchlist (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol TEXT NOT NULL,
      reason TEXT,
      upside_potential NUMERIC,
      created_at TIMESTAMPTZ DEFAULT NOW()
  );
`;

async function migrate() {
    console.log("Attempting to create 'ai_watchlist' table...");

    // We cannot execute raw DDL like CREATE TABLE directly with supabase-js rpc.
    // We need to create a function in the database first and then call it.
    // Since we can't run migrations, we'll try a different approach.
    // Let's try to select from the table. If it fails, it likely doesn't exist.
    // This is not a perfect solution, but it's a good diagnostic step.

    const { data, error } = await supabase.from('ai_watchlist').select('*').limit(1);

    if (error) {
        if (error.code === '42P01') { // 42P01 is "undefined_table"
            console.error("Error: The 'ai_watchlist' table does not exist.");
            console.error("The migration to create it has failed repeatedly.");
            console.error("Please resolve the migration issue in your Supabase project or create the table manually in the Supabase dashboard.");
            process.exit(1);
        } else {
            console.error("An unexpected error occurred when checking for 'ai_watchlist':", error);
            process.exit(1);
        }
    } else {
        console.log("'ai_watchlist' table already exists. Migration not needed.");
    }
}

console.log("This script is a diagnostic check. It cannot create the table directly due to security restrictions in supabase-js.");
console.log("It will check if the 'ai_watchlist' table exists.");

migrate();
