import pg from 'pg';
import dns from 'dns';
import { promisify } from 'util';

const { Client } = pg;
const lookup = promisify(dns.lookup);

const dbHost = 'db.bahshstcztvqmxiubslx.supabase.co';

async function migrate() {
  let client;
  try {
    const { address } = await lookup(dbHost, { family: 4 });
    console.log(`Resolved IPv4 address: ${address}`);

    const connectionString = `postgres://postgres:${process.env.SUPABASE_DB_PASSWORD}@${address}:5432/postgres`;
    client = new Client({ connectionString });

    const createTableSql = `
      CREATE TABLE public.ai_watchlist (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          symbol TEXT NOT NULL,
          reason TEXT,
          upside_potential NUMERIC,
          created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;

    await client.connect();
    console.log('Connected to the database.');

    await client.query(createTableSql);
    console.log("Table 'ai_watchlist' created successfully.");

  } catch (err) {
    if (err.code === '42P07') { // 42P07 is the error code for "duplicate_table"
      console.log("Table 'ai_watchlist' already exists. Skipping creation.");
    } else {
      console.error('Error during migration:', err);
      process.exit(1); // Exit with error
    }
  } finally {
    if (client) {
      await client.end();
      console.log('Connection closed.');
    }
  }
}

migrate();