
import { Client } from "https://deno.land/x/postgres/mod.ts";

const client = new Client({
  user: "postgres",
  password: Deno.env.get("SUPABASE_DB_PASSWORD"),
  database: "postgres",
  hostname: "db.bahshstcztvqmxiubslx.supabase.co",
  port: 5432,
});

await client.connect();

const sql = `
  CREATE TABLE public.ai_watchlist (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      symbol TEXT NOT NULL,
      reason TEXT,
      upside_potential NUMERIC,
      created_at TIMESTAMPTZ DEFAULT NOW()
  );
`;

try {
  await client.queryArray(sql);
  console.log("Table 'ai_watchlist' created successfully.");
} catch (e) {
  if (e.message.includes('relation "ai_watchlist" already exists')) {
    console.log("Table 'ai_watchlist' already exists.");
  } else {
    console.error("Error creating table:", e);
    Deno.exit(1);
  }
} finally {
  await client.end();
}
