import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

console.log('Hello from Functions!')

Deno.serve(async (req) => {
  try {
    // Create a Supabase client with the Auth context of the logged in user.
    const supabaseClient = createClient(
      // Supabase API URL - env var exported by default.
      Deno.env.get('SUPABASE_URL') ?? '',
      // Supabase API ANON KEY - env var exported by default.
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      // Create client with Auth context of the user that called the function.
      // This way your row-level-security (RLS) policies are applied.
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    )

    const { data, error } = await supabaseClient.rpc('exec', {
      sql: `
        CREATE TABLE public.ai_watchlist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            symbol TEXT NOT-NULL,
            reason TEXT,
            upside_potential NUMERIC,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
      `
    })

    if (error) {
      // Check if the error is because the table already exists
      if (error.message.includes('relation "ai_watchlist" already exists')) {
        return new Response(JSON.stringify({ message: 'Table already exists' }), {
          headers: { 'Content-Type': 'application/json' },
          status: 200,
        })
      }
      throw error
    }

    return new Response(JSON.stringify(data), {
      headers: { 'Content-Type': 'application/json' },
      status: 200,
    })
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: errorMessage }), {
      headers: { 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})