CREATE TABLE public.ai_watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    reason TEXT,
    upside_potential NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
