
export const CATEGORIES = [
  { value: 'all', label: 'All Categories' },
  { value: 'layer1', label: 'Layer 1' },
  { value: 'layer2', label: 'Layer 2' },
  { value: 'defi', label: 'DeFi' },
  { value: 'memecoin', label: 'Memecoins' },
  { value: 'stablecoin', label: 'Stablecoins' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'ai', label: 'AI' },
  { value: 'privacy', label: 'Privacy' },
  { value: 'solana', label: 'Solana Chain' },
  { value: 'ethereum', label: 'ETH Chain' },
  { value: 'bitcoin', label: 'BTC Chain' },
  { value: 'bnb', label: 'BNB Chain' },
  { value: 'rwa', label: 'RWA' },
  { value: 'depin', label: 'DePIN' },
  { value: 'oracles', label: 'Oracles' },
  { value: 'payments', label: 'Payments' },
  { value: 'metaverse', label: 'Metaverse' },
  { value: 'nft', label: 'NFT' },
  { value: 'storage', label: 'Storage' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'cex-token', label: 'CEX Token' },
  { value: 'lst', label: 'LST' },
];

export const TIMEFRAMES = [
  { value: '5m', label: '5 min' },
  { value: '15m', label: '15 min' },
  { value: '30m', label: '30 min' },
  { value: '1h', label: '1 hour' },
  { value: '4h', label: '4 hours' },
  { value: '24h', label: '24 hours' },
  { value: '7d', label: '7 days' },
];
